name: 部署页面
on:
  push:
      branches:
          - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: 设置 Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 20
            cache: 'npm' # 缓存 npm 依赖
        - name: 安装依赖
          run: npm install
        - name: 编译项目
          run: npm run docs:build
        - name: 部署到 服务器
          uses: easingthemes/ssh-deploy@v5.1.0
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            ARGS: "-rlgoDzvc -i --delete"
            SOURCE: "story/.vitepress/dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            EXCLUDE: "/node_modules/"